spring:
  profiles: cloud
server:
  port: ${PORT:5000}
villains:
  ribbon:
    listOfServers: https://rocky-sands-35353.herokuapp.com

---
spring:
  profiles: test, local
villains:
  ribbon:
    listOfServers: localhost:8080
server:
  port: 8081
